// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGDhT5wmYLc1XU_r89YLxVjffy8X4hl0o',
    appId: '1:642318712951:web:b1beee46d9006287c84672',
    messagingSenderId: '642318712951',
    projectId: 'agroapp-28f97',
    authDomain: 'agroapp-28f97.firebaseapp.com',
    storageBucket: 'agroapp-28f97.firebasestorage.app',
    measurementId: 'G-LDGZF0KZS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGqGzF9O7TNgnbZjLu56rkkRTrAiWsO_0',
    appId: '1:642318712951:android:9e1c3f4fbb738481c84672',
    messagingSenderId: '642318712951',
    projectId: 'agroapp-28f97',
    storageBucket: 'agroapp-28f97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBymAoJUxahc8zUYO4Gdc0VvWBhCVtPir8',
    appId: '1:642318712951:ios:ccecb3476eaa63e1c84672',
    messagingSenderId: '642318712951',
    projectId: 'agroapp-28f97',
    storageBucket: 'agroapp-28f97.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBymAoJUxahc8zUYO4Gdc0VvWBhCVtPir8',
    appId: '1:642318712951:ios:ccecb3476eaa63e1c84672',
    messagingSenderId: '642318712951',
    projectId: 'agroapp-28f97',
    storageBucket: 'agroapp-28f97.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGDhT5wmYLc1XU_r89YLxVjffy8X4hl0o',
    appId: '1:642318712951:web:883c5c2eb3fe925fc84672',
    messagingSenderId: '642318712951',
    projectId: 'agroapp-28f97',
    authDomain: 'agroapp-28f97.firebaseapp.com',
    storageBucket: 'agroapp-28f97.firebasestorage.app',
    measurementId: 'G-LVP2F6BB9V',
  );
}
